### PR TITLE
Lint the script tag.

### PR DESCRIPTION
**Pull request by robinlarsson**
https://eslint.vuejs.org/rules/script-indent.html

### CODE REVIEW

**Comment by GustaMagik** [comment]
Super nice, does es lint run automatically or is it triggered manually?

**Comment by robinlarsson** [comment]
> Super nice, does es lint run automatically or is it triggered manually?

Not at the moment. Currently, the developer have to configure their IDE for the lint to run automatically.

Another way is to setup a git-commit hook to lint automatically, but that also requires manual setup.

Do you know of any fully automated way for lint?

**Comment by Zomis** [comment]
What is the command to run the linting? (Just verification, no fixing). I can add it as a build step on Jenkins

**Comment by robinlarsson** [comment]
> What is the command to run the linting? (Just verification, no fixing). I can add it as a build step on Jenkins

In this PR, the script `npm run validate` is added.

**Comment by Zomis** [comment]
Cherry-picked!

**Pull request closed without merging**
